import { repoVarient, roboAnimation } from "@/utils/animations";
import {
  Box,
  Flex,
  Stack,
  Text,
  useColorModeValue,
  Image as ImageN,
} from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import roboGear from "../pics/robo-gear.svg";
import {motion} from "framer-motion";

const Error = () => {
  return (
    <>
      <Head>
        <title>Amr Kakashi | 404</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack
        w={"100%"}
        height={"100%"}
        bg={useColorModeValue("gray.200", "gray.700")}
        px={10}
        display="flex"
        align={"center"}
        justify="center"
      >
        <Box w="100%" h="90%" p="8" marginBottom="20px">
          <motion.div
          variants={repoVarient}
          initial="textUpStart"
          animate="textUpEnd"
          transition={{delay:0.3, duration:0.6, type:"spring", stiffness:120}}
          >
          <Text
            fontSize={{ sm: "20", md: "30", lg: "40" }}
            fontWeight="700"
            textAlign="center"
            h="50px"
          >
            OOPS !!!
          </Text>
            </motion.div>

            <motion.div
          variants={repoVarient}
          initial="textUpStart"
          animate="textUpEnd"
          transition={{delay:0.2, duration:0.6, type:"spring", stiffness:120}}
          >

          <Text
            fontSize={{ sm: "20", md: "30", lg: "40" }}
            fontWeight="700"
            textAlign="center"
            h="50px"
          >
            This Page Does Not Exsist !!!
          </Text>
          </motion.div>

          <motion.div 
            variants={repoVarient}
            initial="start"
            animate="end"
            transition={{delay:0.2, duration:0.7, type:"spring", stiffness:120}}
          >
          <Flex
            w={{
              base: "30%",
              md: "30%",
              sm: "100%",
              isSmallerThn300px: "100%",
            }}
            justify="center"
            marginTop="50px"
          >
            <ImageN
              as={Image}
              w="250px"
              objectFit="cover"
              src={roboGear}
              animation={roboAnimation}
            />
          </Flex>
          </motion.div>
        </Box>
      </Stack>
    </>
  );
};

export default Error;
