import React from "react";
import {
  Box,
  Flex,
  Image as ImageN,
  Stack,
  Text,
  Icon,
  Center,
  useColorModeValue,
} from "@chakra-ui/react";
import robophone from "../pics/robo-phone.svg";
import {
  FaFacebook,
  FaGithub,
  FaGooglePlusSquare,
  FaLinkedin,
  FaWhatsapp,
} from "react-icons/fa";
import { useMediaQuery } from "@chakra-ui/react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";
import { divVarient, roboAnimation } from "@/utils/animations";
import { motion } from "framer-motion";

function Contact() {
  const [isSmallerThn300px] = useMediaQuery("(max-width: 300px)");
  return (
    <>
      <Head>
        <title>Amr Kakashi | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack
        w="100%"
        minH={"100%"}
        bg={useColorModeValue("gray.200", "gray.600")}
        px={10}
        py={55}
      >
        <Box w="100%" pos={"relative"}>
          <Center
            className="text"
            fontSize="90"
            fontWeight="700"
            textAlign="center"
            h="90px"
            pos={"absolute"}
            top="50%"
            w="100%"
            zIndex="0"
            color={useColorModeValue("gray.300", "gray.700")}
            letterSpacing="1.5"
          >
            CONTACT ME
          </Center>
          <Flex
            className="contact"
            align="center"
            justify="center"
            wrap="wrap"
            my="5"
            flexDir={{ md: "row", sm: "column" }} // dont forget to make extra small
          >
            <Flex w={{ md: "40%", sm: "100%" }} zIndex="5" justify="center">
              <motion.div
                variants={divVarient}
                initial="roboStart"
                animate="roboEnd"
                transition={{
                  delay: 0.5,
                  duration: 1.5,
                  type: "spring",
                  stiffness: 120,
                }}
              >
                <ImageN
                  as={Image}
                  alt="noooo"
                  className="robo"
                  w="250"
                  objectFit="cover"
                  src={robophone}
                  animation={roboAnimation}
                />
              </motion.div>
            </Flex>

            <Flex
              justify="center"
              align="center"
              wrap="wrap"
              w={{ md: "60%", sm: "100%" }}
              gap="8"
              zIndex="5"
            >
              {socials.map((social) => (
                <motion.div
                  key={social.id}
                  variants={divVarient}
                  initial="skillStart"
                  animate="skillEnd"
                  transition={{
                    delay: 0.5,
                    duration: 1.5,
                    type: "spring",
                    stiffness: 120,
                  }}
                >
                  <Box
                    as={Link}
                    href={social.link}
                    target="_blank"
                    key={social.id}
                    border="1px"
                    borderRadius="lg"
                    display="flex"
                    alignItems="center"
                    justifyContent="space-around"
                    flexDir="column"
                    boxShadow="2xl"
                    p="5"
                    w="210px"
                    minH="220px"
                    m="3"
                    _hover={{ color: `${social.color}.600` }}
                  >
                    <Box fontSize="50" color={`${social.color}.600`}>
                      {social.icon}
                    </Box>
                    {/* <Icon as={MdSettings} /> */}
                    <Text fontSize={25} fontWeight={700}>
                      {social.name}
                    </Text>
                    <Text fontWeight={500} textAlign={"center"} py="5">
                      {social.p}
                    </Text>
                  </Box>
                </motion.div>
              ))}
            </Flex>
          </Flex>
        </Box>
      </Stack>
    </>
  );
}

export default Contact;

export const socials = [
  {
    id: Math.random(),
    color: "green",
    name: "Whatsapp",
    link: "https://wa.me/0201029404662",
    icon: <Icon as={FaWhatsapp} />,
    p: `Text me via WhatsApp`,
  },
  {
    id: Math.random(),
    color: "blue",
    name: "Facebook",
    link: "https://www.facebook.com/93amr.kakashi/",
    icon: <Icon as={FaFacebook} />,
    p: `Visit me on Facebook.`,
  },
  {
    id: Math.random(),
    color: "blue",
    name: "LinkedIn",
    link: "https://www.linkedin.com/in/amr-ali-mohamed-88192b241/",
    icon: <Icon as={FaLinkedin} />,
    p: `Hire me on LinkedIn.`,
  },
  {
    id: Math.random(),
    color: "red",
    name: "Gmail",
    link: "mailto:93amr.kakashi@gmail.com",
    icon: <Icon as={FaGooglePlusSquare} />,
    p: `Email me via Gmail.`,
  },
  {
    id: Math.random(),
    color: "blackAlpha",
    name: "GitHub",
    link: "https://github.com/93amrkakashi",
    icon: <Icon as={FaGithub} />,
    p: `Visit my GitHub to see more.`,
  },
];
