import Head from 'next/head'
import Image from 'next/image'
import {
  Stack,
  Flex,
  Heading,
  Text,
  Button,
  Image as ImageN,
  useColorModeValue,
} from "@chakra-ui/react";
import Link from 'next/link'
import roboHi from "../pics/robo-hi.svg";
import { roboAnimation } from '@/utils/animations'
import { motion } from 'framer-motion';


export default function Home() {
  return (
    <>
      <Head>
        <title>Amr Kakashi | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack
        w="100%"
        h="100%"
        bg={useColorModeValue("gray.200", "gray.700")}
        px={10}
      >
          <Stack
            align={"center"}
            spacing={{ base: 8, md: 10 }}
            py={{ base: 10, md: 18 }}
            direction={{ base: "column", md: "row" }}
          >
            <Stack  flex={1} spacing={{ base: 5, md: 10 }}>
              <Heading
                lineHeight={1.1}
                fontWeight={600}
                fontSize={{ base: "3xl", sm: "4xl", lg: "6xl" }}
              >
                <motion.div
                
                style={{display:"inline-block"}}
                initial={{x:"-50vw", y:"-50vh"}}
                animate={{x:"0", y:"0"}}
                transition ={{ delay:0.5,duration:0.9, type: "spring"}}
                >
                  Hi There ...!
                </motion.div>
                <br />
                <Text as={"span"} color={"blue.400"}>
                  I am{"  "}
                </Text>
                <Text
                  as={motion.span}
                  whileHover={{x:10}}
                  // animation={{x:10}}
                  display='inline-block'
                  position={"relative"}
                  zIndex= {9}
                  _after={{
                    content: "''",
                    width: "full",
                    height: "30%",
                    position: "absolute",
                    bottom: 1,
                    left: 0,
                    bg: "blue.700",
                    zIndex: -1,
                  }}
                >
                  Amr Ali
                </Text>
              </Heading>
              <Text colorScheme={"facebook"} fontSize="22">
                A React.js Frontend Web Developer. <br />
                 I am a rising talent in the web development world. <br />
                 I have a passion for developing
                and designing web applications and exploring more in this world
                that I love.
                <br />I like using React to build responsive websites that are
                responsive to all screens, and I have a constant thirst for
                problem solving and getting into programming challenges.
              </Text>
              <Stack
                spacing={{ base: 4, sm: 6 }}
                direction={{ base: "column", sm: "row" }}
              >
                <Button
                  as={Link}
                  href={"/About"}
                  rounded={"full"}
                  size={"lg"}
                  fontWeight={"normal"}
                  px={6}
                  colorScheme={"blue"}
                  bg={"blue.400"}
                  _hover={{ bg: "blue.500" }}
                >
                  More About Me
                </Button>
              </Stack>
            </Stack>
            <Flex
              flex={1}
              justify={"center"}
              align={"center"}
              position={"relative"}
              w={{ base: "100%", md: "100", sm: "50%" }}
            >
              <ImageN
              as={Image}
              w="250"
              objectFit="cover"
              alt="noooo"
                fit={"cover"}
                align={"center"}
                src={roboHi}
                animation={roboAnimation}
              />
            </Flex>
          </Stack>
        </Stack>
    </>
  )
}
